# Generated by Django 2.1.4 on 2019-04-29 16:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190429_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
